# Generated by Django 4.2.16 on 2024-11-18 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_remove_internship_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='apply_url',
            field=models.URLField(blank=True, null=True, verbose_name='Apply URL'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.internshipcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='full_description',
            field=models.TextField(verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='internships/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='additional_titles',
            field=models.JSONField(default=dict, verbose_name='Additional Titles'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Applied At'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='file',
            field=models.FileField(max_length=255, upload_to='apply/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.internship', verbose_name='Internship'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='internshipcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
